services:
  api:
    build: 
      context: ../Servidor-Local
    container_name: servidor-local
    ports:
      - 8000:8000

    networks:
      - marketplace-net

    environment:
      - PORT=8000
      - NODE_ENV=development

  web:
    build: 
      context: .
    container_name: servidor-local-front
    ports:
      - "3000:3000"

    networks:
      - marketplace-net

    depends_on:
      - api

    environment:
      - PORT=3000
      - NEXT_PUBLIC_DATA_API_URL=http://api:8000/graphql
      - NEXT_PUBLIC_AUTH_API_URL=http://api:8000/

networks:
  marketplace-net:
    driver: bridge
